### ISSUE TITLE
Infinite recursion between django-modeltranslations and django-cleanup

### ISSUE THREAD

**Issue by Paul424** [un1t/django-cleanup#36] opened 2017-04-07 12:06 UTC
Not sure if it's related to a recent upgrade to django 1.10 but there is an infinite recursion between django-cleanup and django modeltranslations.

django-cleanup==0.4.2
django-modeltranslation==0.12
Django==1.10

  File "/site/env/python/local/lib/python2.7/site-packages/django/db/models/base.py", line 557, in __init__
    signals.post_init.send(sender=self.__class__, instance=self)
  File "/site/env/python/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/site/env/python/local/lib/python2.7/site-packages/django_cleanup/handlers.py", line 44, in cache_original_post_init
    cache.make_cleanup_cache(instance)
  File "/site/env/python/local/lib/python2.7/site-packages/django_cleanup/cache.py", line 165, in make_cleanup_cache
    fields_for_model_instance(source, using=instance)))
  File "/site/env/python/local/lib/python2.7/site-packages/django_cleanup/cache.py", line 108, in fields_for_model_instance
    field = get_field_instance(instance, field_name, using=using)
  File "/site/env/python/local/lib/python2.7/site-packages/django_cleanup/cache.py", line 82, in get_field_instance
    field = getattr(instance, field_name, None)
  File "/site/env/python/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 173, in __get__
    instance.refresh_from_db(fields=[self.field.name])
  File "/site/env/python/local/lib/python2.7/site-packages/modeltranslation/translator.py", line 304, in new_refresh_from_db
    return old_refresh_from_db(self, using, fields)
  File "/site/env/python/local/lib/python2.7/site-packages/django/db/models/base.py", line 685, in refresh_from_db
    db_instance = db_instance_qs.get()
  File "/site/env/python/local/lib/python2.7/site-packages/django/db/models/query.py", line 379, in get
    num = len(clone)
  File "/site/env/python/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in __len__
    self._fetch_all()
  File "/site/env/python/local/lib/python2.7/site-packages/django/db/models/query.py", line 1085, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/site/env/python/local/lib/python2.7/site-packages/django/db/models/query.py", line 66, in __iter__
    obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
  File "/site/env/python/local/lib/python2.7/site-packages/django/db/models/base.py", line 565, in from_db
    new = cls(*values)
  File "/site/env/python/local/lib/python2.7/site-packages/modeltranslation/translator.py", line 245, in new_init
    old_init(self, *args, **kwargs)
  File "/site/env/python/local/lib/python2.7/site-packages/django/db/models/base.py", line 557, in __init__
    signals.post_init.send(sender=self.__class__, instance=self)

**Comment by vinnyrose** [comment] 2017-04-07 12:42
django is unable to find the field name in `__dict__`:
https://github.com/django/django/blob/master/django/db/models/fields/files.py#L167
And is then running `instance.refresh_from_db`, which is causing another init to occur.

In django-modeltranslation they do a lot of monkey patching of model fields, not sure if that is why the field name is not able to be found.

**Comment by Paul424** [comment] 2017-04-09 19:42
I did some debugging and found that this model has 2 image fields; when it triggers to """new_init""" from db i can see that not all fields are loaded, only a few + 1 of the image fields. Then another init cycle is triggered; i guess for the other image field but the result is that the other image field is loaded but the other is lost in the process, so we end up in the loop.

**Comment by vinnyrose** [comment] 2017-04-10 00:05
If you remove `django_cleanup` from installed apps and do the following, replacing `filefield1`, `filefield2` and `models.Model` with the values specific to your model, do you get the same result?

    from django.db.models.signals import post_init

    from . import models


    def post_init_handler(sender, instance, **kwargs):
        filefield1 = instance.filefield1
        filefield2 = instance.filefield2
    post_init.connect(post_init_handler, sender=models.Model)

**Comment by Paul424** [comment] 2017-04-12 21:41
I need to check.... however i'm also fine with removal of cleanup
altogether for now; you see with media pushed to s3, given the low prices
doesn't really put this item on the top of my list; once i get many many
many customers,,,,, ;-). Also actually i don't like messing with signals
too much.
Paul


2017-04-10 2:05 GMT+02:00 vinnyrose <notifications@github.com>:

**Comment by vinnyrose** [comment] 2017-06-16 12:21
If you were using deferred fields in your model then this will be fixed soon. Django 1.10 changed how deferred fields are handled, and we never really handled them that well since there was an outstanding bug in Django that prevented the correct expected behavior.

**Comment by vinnyrose** [comment] 2017-06-30 14:21
Fixed in fff32f5.

**Closed by vinnyrose** 2017-06-30 14:21 UTC
Labels: bug
